// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 16.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GakujoGUI
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class Index : IndexBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n<!DOCTYPE html>\r\n<html lang=\"ja\">\r\n\r\n<head>\r\n  <meta charset=\"utf-8\">\r\n  <meta " +
                    "name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n  <link href=\"ht" +
                    "tps://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"styl" +
                    "esheet\"\r\n    integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65" +
                    "VohhpuuCOmLASjC\" crossorigin=\"anonymous\">\r\n  <script src=\"https://code.jquery.co" +
                    "m/jquery-3.6.0.min.js\"\r\n    integrity=\"sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7o" +
                    "gEvDej/m4=\" crossorigin=\"anonymous\"></script>\r\n  <style>\r\n    body {\r\n      marg" +
                    "in: 10px;\r\n      overflow: hidden;\r\n    }\r\n\r\n    #main-tab {\r\n      width: 180px" +
                    ";\r\n    }\r\n\r\n    #main-tab-content {\r\n      width: calc(100vw - 240px);\r\n    }\r\n\r" +
                    "\n    #main-tab-content form {\r\n      max-width: 600px;\r\n    }\r\n\r\n    #classconta" +
                    "ct-tab,\r\n    #schoolcontact-tab {\r\n      height: 95vh;\r\n      overflow-x: hidden" +
                    ";\r\n      overflow-y: auto;\r\n    }\r\n\r\n    .text-wrap {\r\n      overflow: hidden;\r\n" +
                    "      text-overflow: ellipsis;\r\n      white-space: nowrap !important;\r\n    }\r\n  " +
                    "</style>\r\n</head>\r\n\r\n<body>\r\n  <div class=\"d-flex align-items-start\">\r\n    <div " +
                    "class=\"nav flex-column nav-pills me-3\" id=\"main-tab\" role=\"tablist\" aria-orienta" +
                    "tion=\"vertical\">\r\n      <button class=\"nav-link active\" id=\"main-tab-login\" data" +
                    "-bs-toggle=\"pill\" data-bs-target=\"#main-login\"\r\n        type=\"button\" role=\"tab\"" +
                    " aria-controls=\"main-login\" aria-selected=\"true\">\r\n        ログイン\r\n      </button>" +
                    "\r\n      <button class=\"nav-link\" id=\"main-tab-classcontact\" data-bs-toggle=\"pill" +
                    "\" data-bs-target=\"#main-classcontact\"\r\n        type=\"button\" role=\"tab\" aria-con" +
                    "trols=\"main-classcontact\" aria-selected=\"false\">\r\n        授業連絡\r\n      </button>\r" +
                    "\n      <button class=\"nav-link\" id=\"main-tab-report\" data-bs-toggle=\"pill\" data-" +
                    "bs-target=\"#main-report\" type=\"button\"\r\n        role=\"tab\" aria-controls=\"main-r" +
                    "eport\" aria-selected=\"false\">\r\n        レポート\r\n      </button>\r\n      <button clas" +
                    "s=\"nav-link\" id=\"main-tab-quiz\" data-bs-toggle=\"pill\" data-bs-target=\"#main-quiz" +
                    "\" type=\"button\"\r\n        role=\"tab\" aria-controls=\"main-quiz\" aria-selected=\"fal" +
                    "se\">\r\n        小テスト\r\n      </button>\r\n      <button class=\"nav-link\" id=\"main-tab" +
                    "-schoolcontact\" data-bs-toggle=\"pill\" data-bs-target=\"#main-schoolcontact\"\r\n    " +
                    "    type=\"button\" role=\"tab\" aria-controls=\"main-schoolcontact\" aria-selected=\"f" +
                    "alse\">\r\n        学内連絡\r\n      </button>\r\n      <button class=\"nav-link\" id=\"main-t" +
                    "ab-classfile\" data-bs-toggle=\"pill\" data-bs-target=\"#main-classfile\"\r\n        ty" +
                    "pe=\"button\" role=\"tab\" aria-controls=\"main-classfile\" aria-selected=\"false\">\r\n  " +
                    "      授業共有ファイル\r\n      </button>\r\n      <button class=\"nav-link\" id=\"main-tab-sch" +
                    "oolfile\" data-bs-toggle=\"pill\" data-bs-target=\"#main-schoolfile\"\r\n        type=\"" +
                    "button\" role=\"tab\" aria-controls=\"main-schoolfile\" aria-selected=\"false\">\r\n     " +
                    "   学内共有ファイル\r\n      </button>\r\n    </div>\r\n    <div class=\"tab-content\" id=\"main-" +
                    "tab-content\">\r\n      <div class=\"tab-pane fade show active\" id=\"main-login\" role" +
                    "=\"tabpanel\" aria-labelledby=\"main-tab-login\">\r\n        <form class=\"row g-3\">\r\n " +
                    "         <div class=\"row my-3\">\r\n            <label for=\"login-id\" class=\"col-sm" +
                    "-2 col-form-label\">静大ID</label>\r\n            <div class=\"col-sm-10\">\r\n          " +
                    "    <input type=\"text\" class=\"form-control\" id=\"login-id\" placeholder=\"\">\r\n     " +
                    "       </div>\r\n          </div>\r\n          <div class=\"row mb-3\">\r\n            <" +
                    "label for=\"login-password\" class=\"col-sm-2 col-form-label\">パスワード</label>\r\n      " +
                    "      <div class=\"col-sm-10\">\r\n              <input type=\"password\" class=\"form-" +
                    "control\" id=\"login-password\" placeholder=\"\">\r\n            </div>\r\n          </di" +
                    "v>\r\n          <div class=\"row mb-3\">\r\n            <label for=\"login-name\" class=" +
                    "\"col-sm-2 col-form-label\">氏名</label>\r\n            <div class=\"col-sm-10\">\r\n     " +
                    "         <input type=\"text\" class=\"form-control\" id=\"login-name\" placeholder=\"\">" +
                    "\r\n            </div>\r\n          </div>\r\n          <div class=\"row mb-3\">\r\n      " +
                    "      <label for=\"login-number\" class=\"col-sm-2 col-form-label\">学籍番号</label>\r\n  " +
                    "          <div class=\"col-sm-10\">\r\n              <input type=\"text\" class=\"form-" +
                    "control\" id=\"login-number\" placeholder=\"\">\r\n            </div>\r\n          </div>" +
                    "\r\n          <div class=\"row mb-12\">\r\n            <button type=\"button\" class=\"bt" +
                    "n btn-primary\"\r\n              onclick=\"window.chrome.webview.postMessage(\'login\'" +
                    ");\">ログイン</button>\r\n          </div>\r\n        </form>\r\n      </div>\r\n      <div c" +
                    "lass=\"tab-pane fade\" id=\"main-classcontact\" role=\"tabpanel\" aria-labelledby=\"mai" +
                    "n-tab-classcontact\">\r\n        <button type=\"button\" class=\"btn btn-primary m-2\"\r" +
                    "\n          onclick=\"window.chrome.webview.postMessage(\'refresh-classcontact\');\">" +
                    "更新</button>\r\n        <div class=\"row\">\r\n          <div class=\"col-4\">\r\n         " +
                    "   <div class=\"list-group\" id=\"classcontact-tab\" role=\"tablist\">\r\n              " +
                    "");
            
            #line 121 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
 int classContactListIndex = 0; 
            
            #line default
            #line hidden
            this.Write("              ");
            
            #line 122 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
 foreach(var item in IndexData.ClassContactList) { 
            
            #line default
            #line hidden
            this.Write("              ");
            
            #line 123 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
 classContactListIndex++; 
            
            #line default
            #line hidden
            this.Write("              <a class=\"list-group-item list-group-item-action\" id=\"classcontact-" +
                    "tab-");
            
            #line 124 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(classContactListIndex));
            
            #line default
            #line hidden
            this.Write("\" data-bs-toggle=\"list\"\r\n                href=\"#classcontact-");
            
            #line 125 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(classContactListIndex));
            
            #line default
            #line hidden
            this.Write("\" role=\"tab\" aria-controls=\"classcontact-");
            
            #line 125 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(classContactListIndex));
            
            #line default
            #line hidden
            this.Write("\">\r\n                <div class=\"d-flex w-100 justify-content-between\">\r\n         " +
                    "         <h5 class=\"mb-1\">");
            
            #line 127 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.title));
            
            #line default
            #line hidden
            this.Write("</h5>\r\n                  <small>");
            
            #line 128 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.contactTime));
            
            #line default
            #line hidden
            this.Write("</small>\r\n                </div>\r\n                <p class=\"mb-1 text-wrap\">");
            
            #line 130 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.content));
            
            #line default
            #line hidden
            this.Write("</p>\r\n                <small>");
            
            #line 131 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.classSubjects));
            
            #line default
            #line hidden
            this.Write("</small>\r\n              </a>\r\n              ");
            
            #line 133 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            </div>\r\n          </div>\r\n          <div class=\"col-8\">\r\n            " +
                    "<div class=\"tab-content\" id=\"classcontact-tab-content\">\r\n              ");
            
            #line 138 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
 classContactListIndex = 0; 
            
            #line default
            #line hidden
            this.Write("              ");
            
            #line 139 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
 foreach(var item in IndexData.ClassContactList) { 
            
            #line default
            #line hidden
            this.Write("              ");
            
            #line 140 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
 classContactListIndex++; 
            
            #line default
            #line hidden
            this.Write("              <div class=\"tab-pane fade\" id=\"classcontact-");
            
            #line 141 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(classContactListIndex));
            
            #line default
            #line hidden
            this.Write("\" role=\"tabpanel\" aria-labelledby=\"classcontact-tab-");
            
            #line 141 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(classContactListIndex));
            
            #line default
            #line hidden
            this.Write("\">\r\n                <div class=\"card\">\r\n                  <div class=\"card-body\">" +
                    "\r\n                    <h5 class=\"card-title\">");
            
            #line 144 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.title));
            
            #line default
            #line hidden
            this.Write("</h5>\r\n                    <h6 class=\"card-subtitle mb-2 text-muted\">");
            
            #line 145 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.contactTime));
            
            #line default
            #line hidden
            this.Write("</h6>\r\n                    <p class=\"card-text\">");
            
            #line 146 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.content));
            
            #line default
            #line hidden
            this.Write("\r\n                    </p>\r\n                    <a href=\"#\" class=\"card-link\">");
            
            #line 148 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.file));
            
            #line default
            #line hidden
            this.Write("</a>\r\n                  </div>\r\n                </div>\r\n              </div>\r\n   " +
                    "           ");
            
            #line 152 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"            </div>
          </div>
        </div>
      </div>
      <div class=""tab-pane fade"" id=""main-report"" role=""tabpanel"" aria-labelledby=""main-tab-report"">
        <button type=""button"" class=""btn btn-primary m-2""
          onclick=""window.chrome.webview.postMessage('refresh-report');"">更新</button>
        <table class=""table table-hover"">
          <thead>
            <tr>
              <th scope=""col"">授業科目</th>
              <th scope=""col"">タイトル</th>
              <th scope=""col"">状態</th>
              <th scope=""col"">提出期間</th>
              <th scope=""col"">最終提出日時</th>
              <th scope=""col"">操作</th>
            </tr>
          </thead>
          <tbody>
            ");
            
            #line 172 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
 foreach(var item in IndexData.ReportList) { 
            
            #line default
            #line hidden
            this.Write("            <tr>\r\n              <td>");
            
            #line 174 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.classSubjects));
            
            #line default
            #line hidden
            this.Write("</td>\r\n              <td>");
            
            #line 175 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.title));
            
            #line default
            #line hidden
            this.Write("</td>\r\n              <td>");
            
            #line 176 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.status));
            
            #line default
            #line hidden
            this.Write("</td>\r\n              <td>");
            
            #line 177 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.submissionPeriod));
            
            #line default
            #line hidden
            this.Write("</td>\r\n              <td>");
            
            #line 178 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.lastSubmissionTime));
            
            #line default
            #line hidden
            this.Write("</td>\r\n              <td>");
            
            #line 179 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.operation));
            
            #line default
            #line hidden
            this.Write("</td>\r\n            </tr>\r\n            ");
            
            #line 181 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"          </tbody>
        </table>
      </div>
      <div class=""tab-pane fade"" id=""main-quiz"" role=""tabpanel"" aria-labelledby=""main-tab-quiz"">
        <button type=""button"" class=""btn btn-primary m-2""
          onclick=""window.chrome.webview.postMessage('refresh-quiz');"">更新</button>
        <table class=""table table-hover"">
          <thead>
            <tr>
              <th scope=""col"">授業科目</th>
              <th scope=""col"">タイトル</th>
              <th scope=""col"">状態</th>
              <th scope=""col"">提出期間</th>
              <th scope=""col"">提出状態</th>
              <th scope=""col"">操作</th>
            </tr>
          </thead>
          <tbody>
            ");
            
            #line 200 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
 foreach(var item in IndexData.QuizList) { 
            
            #line default
            #line hidden
            this.Write("            <tr>\r\n              <td>");
            
            #line 202 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.classSubjects));
            
            #line default
            #line hidden
            this.Write("</td>\r\n              <td>");
            
            #line 203 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.title));
            
            #line default
            #line hidden
            this.Write("</td>\r\n              <td>");
            
            #line 204 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.status));
            
            #line default
            #line hidden
            this.Write("</td>\r\n              <td>");
            
            #line 205 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.submissionPeriod));
            
            #line default
            #line hidden
            this.Write("</td>\r\n              <td>");
            
            #line 206 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.submissionStatus));
            
            #line default
            #line hidden
            this.Write("</td>\r\n              <td>");
            
            #line 207 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.operation));
            
            #line default
            #line hidden
            this.Write("</td>\r\n            </tr>\r\n            ");
            
            #line 209 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"          </tbody>
        </table>
      </div>
      <div class=""tab-pane fade"" id=""main-schoolcontact"" role=""tabpanel"" aria-labelledby=""main-tab-schoolcontact"">
        <button type=""button"" class=""btn btn-primary m-2""
          onclick=""window.chrome.webview.postMessage('refresh-schoolcontact');"">更新</button>
        <div class=""row"">
          <div class=""col-4"">
            <div class=""list-group"" id=""schoolcontact-tab"" role=""tablist"">
              ");
            
            #line 219 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
 int schoolContactListIndex = 0; 
            
            #line default
            #line hidden
            this.Write("              ");
            
            #line 220 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
 foreach(var item in IndexData.SchoolContactList) { 
            
            #line default
            #line hidden
            this.Write("              ");
            
            #line 221 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
 schoolContactListIndex++; 
            
            #line default
            #line hidden
            this.Write("              <a class=\"list-group-item list-group-item-action\" id=\"schoolcontact" +
                    "-tab-");
            
            #line 222 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(schoolContactListIndex));
            
            #line default
            #line hidden
            this.Write("\" data-bs-toggle=\"list\"\r\n                href=\"#schoolcontact-");
            
            #line 223 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(schoolContactListIndex));
            
            #line default
            #line hidden
            this.Write("\" role=\"tab\" aria-controls=\"schoolcontact-");
            
            #line 223 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(schoolContactListIndex));
            
            #line default
            #line hidden
            this.Write("\">\r\n                <div class=\"d-flex w-100 justify-content-between\">\r\n         " +
                    "         <h5 class=\"mb-1\">");
            
            #line 225 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.title));
            
            #line default
            #line hidden
            this.Write("</h5>\r\n                  <small>");
            
            #line 226 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.contactTime));
            
            #line default
            #line hidden
            this.Write("</small>\r\n                </div>\r\n                <p class=\"mb-1 text-wrap\">");
            
            #line 228 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.content));
            
            #line default
            #line hidden
            this.Write("</p>\r\n                <small>");
            
            #line 229 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.category));
            
            #line default
            #line hidden
            this.Write("</small>\r\n              </a>\r\n              ");
            
            #line 231 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            </div>\r\n          </div>\r\n          <div class=\"col-8\">\r\n            " +
                    "<div class=\"tab-content\" id=\"schoolcontact-tab-content\">\r\n              ");
            
            #line 236 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
 schoolContactListIndex = 0; 
            
            #line default
            #line hidden
            this.Write("              ");
            
            #line 237 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
 foreach(var item in IndexData.SchoolContactList) { 
            
            #line default
            #line hidden
            this.Write("              ");
            
            #line 238 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
 schoolContactListIndex++; 
            
            #line default
            #line hidden
            this.Write("              <div class=\"tab-pane fade\" id=\"schoolcontact-");
            
            #line 239 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(schoolContactListIndex));
            
            #line default
            #line hidden
            this.Write("\" role=\"tabpanel\" aria-labelledby=\"schoolcontact-tab-");
            
            #line 239 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(schoolContactListIndex));
            
            #line default
            #line hidden
            this.Write("\">\r\n                <div class=\"card\">\r\n                  <div class=\"card-body\">" +
                    "\r\n                    <h5 class=\"card-title\">");
            
            #line 242 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.title));
            
            #line default
            #line hidden
            this.Write("</h5>\r\n                    <h6 class=\"card-subtitle mb-2 text-muted\">");
            
            #line 243 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.contactTime));
            
            #line default
            #line hidden
            this.Write("</h6>\r\n                    <p class=\"card-text\">");
            
            #line 244 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.content));
            
            #line default
            #line hidden
            this.Write("\r\n                    </p>\r\n                    <a href=\"#\" class=\"card-link\">");
            
            #line 246 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.file));
            
            #line default
            #line hidden
            this.Write("</a>\r\n                  </div>\r\n                </div>\r\n              </div>\r\n   " +
                    "           ");
            
            #line 250 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"            </div>
          </div>
        </div>
      </div>
      <div class=""tab-pane fade"" id=""main-classfile"" role=""tabpanel"" aria-labelledby=""main-tab-classfile"">
        <button type=""button"" class=""btn btn-primary m-2""
          onclick=""window.chrome.webview.postMessage('refresh-classfile');"">更新</button>
        <div class=""row"">
          <div class=""col-4"">
            <div class=""list-group"" id=""classfile-tab"" role=""tablist"">
              ");
            
            #line 261 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
 int classFileListIndex = 0; 
            
            #line default
            #line hidden
            this.Write("              ");
            
            #line 262 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
 foreach(var item in IndexData.ClassFileList) { 
            
            #line default
            #line hidden
            this.Write("              ");
            
            #line 263 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
 classFileListIndex++; 
            
            #line default
            #line hidden
            this.Write("              <a class=\"list-group-item list-group-item-action\" id=\"classfile-tab" +
                    "-");
            
            #line 264 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(classFileListIndex));
            
            #line default
            #line hidden
            this.Write("\" data-bs-toggle=\"list\"\r\n                href=\"#classfile-");
            
            #line 265 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(classFileListIndex));
            
            #line default
            #line hidden
            this.Write("\" role=\"tab\" aria-controls=\"classfile-");
            
            #line 265 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(classFileListIndex));
            
            #line default
            #line hidden
            this.Write("\">\r\n                <div class=\"d-flex w-100 justify-content-between\">\r\n         " +
                    "         <h5 class=\"mb-1\">");
            
            #line 267 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.title));
            
            #line default
            #line hidden
            this.Write("</h5>\r\n                  <small>");
            
            #line 268 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.updateTime));
            
            #line default
            #line hidden
            this.Write("</small>\r\n                </div>\r\n                <p class=\"mb-1 text-wrap\">");
            
            #line 270 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.fileDescription));
            
            #line default
            #line hidden
            this.Write("</p>\r\n                <small>");
            
            #line 271 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.classSubjects));
            
            #line default
            #line hidden
            this.Write("</small>\r\n              </a>\r\n              ");
            
            #line 273 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            </div>\r\n          </div>\r\n          <div class=\"col-8\">\r\n            " +
                    "<div class=\"tab-content\" id=\"classfile-tab-content\">\r\n              ");
            
            #line 278 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
 classFileListIndex = 0; 
            
            #line default
            #line hidden
            this.Write("              ");
            
            #line 279 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
 foreach(var item in IndexData.ClassFileList) { 
            
            #line default
            #line hidden
            this.Write("              ");
            
            #line 280 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
 classFileListIndex++; 
            
            #line default
            #line hidden
            this.Write("              <div class=\"tab-pane fade\" id=\"classfile-");
            
            #line 281 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(classFileListIndex));
            
            #line default
            #line hidden
            this.Write("\" role=\"tabpanel\" aria-labelledby=\"classfile-tab-");
            
            #line 281 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(classFileListIndex));
            
            #line default
            #line hidden
            this.Write("\">\r\n                <div class=\"card\">\r\n                  <div class=\"card-body\">" +
                    "\r\n                    <h5 class=\"card-title\">");
            
            #line 284 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.title));
            
            #line default
            #line hidden
            this.Write("</h5>\r\n                    <h6 class=\"card-subtitle mb-2 text-muted\">");
            
            #line 285 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.updateTime));
            
            #line default
            #line hidden
            this.Write("</h6>\r\n                    <p class=\"card-text\">");
            
            #line 286 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.fileDescription));
            
            #line default
            #line hidden
            this.Write("\r\n                    </p>\r\n                    <a href=\"#\" class=\"card-link\">");
            
            #line 288 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.file));
            
            #line default
            #line hidden
            this.Write("</a>\r\n                  </div>\r\n                </div>\r\n              </div>\r\n   " +
                    "           ");
            
            #line 292 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"            </div>
          </div>
        </div>
      </div>
      <div class=""tab-pane fade"" id=""main-schoolfile"" role=""tabpanel"" aria-labelledby=""main-tab-schoolfile"">
        <button type=""button"" class=""btn btn-primary m-2""
          onclick=""window.chrome.webview.postMessage('refresh-schoolfile');"">更新</button>
        <div class=""row"">
          <div class=""col-4"">
            <div class=""list-group"" id=""schoolfile-tab"" role=""tablist"">
              ");
            
            #line 303 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
 int schoolFileListIndex = 0; 
            
            #line default
            #line hidden
            this.Write("              ");
            
            #line 304 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
 foreach(var item in IndexData.SchoolFileList) { 
            
            #line default
            #line hidden
            this.Write("              ");
            
            #line 305 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
 schoolFileListIndex++; 
            
            #line default
            #line hidden
            this.Write("              <a class=\"list-group-item list-group-item-action\" id=\"schoolfile-ta" +
                    "b-");
            
            #line 306 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(schoolFileListIndex));
            
            #line default
            #line hidden
            this.Write("\" data-bs-toggle=\"list\"\r\n                href=\"#schoolfile-");
            
            #line 307 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(schoolFileListIndex));
            
            #line default
            #line hidden
            this.Write("\" role=\"tab\" aria-controls=\"schoolfile-");
            
            #line 307 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(schoolFileListIndex));
            
            #line default
            #line hidden
            this.Write("\">\r\n                <div class=\"d-flex w-100 justify-content-between\">\r\n         " +
                    "         <h5 class=\"mb-1\">");
            
            #line 309 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.title));
            
            #line default
            #line hidden
            this.Write("</h5>\r\n                  <small>");
            
            #line 310 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.updateTime));
            
            #line default
            #line hidden
            this.Write("</small>\r\n                </div>\r\n                <p class=\"mb-1 text-wrap\">");
            
            #line 312 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.fileDescription));
            
            #line default
            #line hidden
            this.Write("</p>\r\n                <small>");
            
            #line 313 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.category));
            
            #line default
            #line hidden
            this.Write("</small>\r\n              </a>\r\n              ");
            
            #line 315 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            </div>\r\n          </div>\r\n          <div class=\"col-8\">\r\n            " +
                    "<div class=\"tab-content\" id=\"schoolfile-tab-content\">\r\n              ");
            
            #line 320 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
 schoolFileListIndex = 0; 
            
            #line default
            #line hidden
            this.Write("              ");
            
            #line 321 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
 foreach(var item in IndexData.SchoolFileList) { 
            
            #line default
            #line hidden
            this.Write("              ");
            
            #line 322 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
 schoolFileListIndex++; 
            
            #line default
            #line hidden
            this.Write("              <div class=\"tab-pane fade\" id=\"schoolfile-");
            
            #line 323 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(schoolFileListIndex));
            
            #line default
            #line hidden
            this.Write("\" role=\"tabpanel\" aria-labelledby=\"schoolfile-tab-");
            
            #line 323 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(schoolFileListIndex));
            
            #line default
            #line hidden
            this.Write("\">\r\n                <div class=\"card\">\r\n                  <div class=\"card-body\">" +
                    "\r\n                    <h5 class=\"card-title\">");
            
            #line 326 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.title));
            
            #line default
            #line hidden
            this.Write("</h5>\r\n                    <h6 class=\"card-subtitle mb-2 text-muted\">");
            
            #line 327 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.updateTime));
            
            #line default
            #line hidden
            this.Write("</h6>\r\n                    <p class=\"card-text\">");
            
            #line 328 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.fileDescription));
            
            #line default
            #line hidden
            this.Write("\r\n                    </p>\r\n                    <a href=\"#\" class=\"card-link\">");
            
            #line 330 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.file));
            
            #line default
            #line hidden
            this.Write("</a>\r\n                  </div>\r\n                </div>\r\n              </div>\r\n   " +
                    "           ");
            
            #line 334 "C:\Users\cs21043\Documents\GitHub\GakujoGUI\GakujoGUI\Index.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <script src=""https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js""
    integrity=""sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p""
    crossorigin=""anonymous""></script>
  <script src=""https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js""
    integrity=""sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF""
    crossorigin=""anonymous""></script>
</body>

</html>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class IndexBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    return "";
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
